language: node_js

branches:
  only:
  - master

node_js: 7

before_script:
- npm install
- npm install -g firebase-tools

script:
- npm run typecheck
- firebase deploy --project weather-scuks --token $FIREBASE_TOKEN
