language: node_js
node_js: 7

jobs:
  include:
    - stage: Typecheck
      script: npm run typecheck
    - stage: Deploy to Firebase
      if: tag IS present
      script: npm install -g firebase-tools && npm run deploy
      on:
        tags: true