language: node_js
node_js: 7

before_script:
- npm install -g firebase-tools

jobs:
  include:
    - stage: Typecheck
      script: npm run typecheck
    - stage: Deploy to Firebase
      if: tag = true
      script: npm run deploy