language: node_js
node_js: 7

jobs:
  include:
    - stage: Typecheck
      script: npm run typecheck
    - stage: Deploy to Firebase
      if: ((tag =~ ^v) AND (branch = master))
      script: npm install -g firebase-tools && npm run deploy
      on:
        tags: true